version: '3.8'

services:
    nginx:
        image: nginx:latest
        ports:
            - '8085:80'
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html

    php:
        image: php:8.3-fpm
        volumes:
            - ./:/var/www/html
